formatter: "markdown table"

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: name
